### ISSUE TITLE
No "Show Changes" option when editing a page, unlike MediaWiki

### ISSUE THREAD

**Issue by James103** [TrueBrain/TrueWiki#372]
Exactly as the title says. In other words, unlike MediaWiki, which was used to power the old OpenTTD wiki and is now used to power Wikipedia and many other wikis, TrueWiki does not have "Show Changes" support as far as I can tell. When editing a page on a wiki powered by TrueWiki, all I see is only "Save page" and "Preview page". Edit a page on Wikipedia, and I get the same two buttons (reworded), plus "Show Changes".

Could "Show Changes" support be added to TrueWiki?

Workaround: Click "Save page", then "View History". If the newly generated commit doesn't appear, wait a few seconds and refresh. Otherwise, open that newly generated commit to view the diff.

**Comment by TrueBrain** [comment]
TrueWiki is not meant to be like MediaWiki. Although the meta-language is the same, and some structural choices are, it otherwise is very opinionated about many subjects. For most functionality we looked at: what makes most sense (to us), and that is what is implemented.

One of those choices is that View History belongs on the View Page, and not on the Edit Page. It only bloats the Edit Page, and doesn't really serve a purpose there. In my opinion, it is sufficient to have the button on one place; I do not see the added value of having it on a second.

So to the question: `Could "Show Changes" support be added to TrueWiki?`, I say: that is implemented by the storage backend, which you can reach via the View Page by pressing View History.
To the question: `No "Show Changes" option when editing a page, unlike MediaWiki`, I say: TrueWiki is not meant to mimic MediaWiki, and I don't see the added value of having "View History" on yet another place.

I guess there is actually a use-case hidden in here somewhere, but the downside of asking a very specific thing, is that you can get a "no" :) Sorry about that :)
