### ISSUE TITLE
Invalid file name results in "page already exists"

### ISSUE THREAD

**Issue by frosch123** [TrueBrain/TrueWiki#57]
1. Create page with name "File/en/Main Page"
2. Error: Page name "File/en/Main Page" already exists.

**Comment by TrueBrain** [comment]
This has nothing to do with an "invalid file name", but is because of "Main Page". As this is our "index.html", in a few namespaces this page is "faked" in order to render roots.

In the `File` and `Category` namespace, every folder has a fake "Main Page".
In the `Template` namespace, on the language root (so in `Template/en/`) there is this fake "Main Page".

This allows rendering of pages like https://wiki.staging.openttd.org/Template/en/ and https://wiki.staging.openttd.org/File/en/ .

So it is more that the error is not correct; the problem is, it depends a bit on the namespace, and I don't have a clean way to separate between: really exists, or was faked. Hmm .. I need to think about this a bit :)
