### ISSUE TITLE
Unlike MediaWiki, there's no search bar or "Special:Random" page.

### ISSUE THREAD

**Issue by James103** [TrueBrain/TrueWiki#86]
Self-explanatory. I miss having the search bar and Special:Random, and it would be great if these features were brought back.

**Comment by TrueBrain** [comment]
Searchbar:
- We will add the searchbar as soon as search engine have picked up the new site

`Special:Random`:
- What would the usecase be? The wiki is not meant to randomly scroll through, but it is meant to give you more information how to play the game. So we don't see added value of `Special:Random`. Of course we can be convinced otherwise, but the information in this ticket doesn't provide any.

In general, please don't create a single ticket with multiple requests. It makes life more complicated than needed. Also, please don't ask for something for the fact of asking, but make clear what your use-case is, etc. This really isn't enough information to pick up, sorry :(
